#!/usr/bin/env node

const readline = require('readline')
const childp = require('child_process')

if (process.argv.length != 3) {
  console.log('Usage: adbPushTo /path/in/your/mobile')
  process.exit(1)
}

const destPath = process.argv[2]

console.log('Using adb to push files to: ' + destPath)

function askForFile(query) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  })

  return new Promise(resolve =>
    rl.question(query, ans => {
      rl.close()
      resolve(ans)
    })
  )
}

;(async function () {
  while (1) {
    const filePath = await askForFile('Please input the file path: \n')

    console.log('Pushing files: ', filePath)

    childp.execSync(`adb push ${filePath} ${destPath}`, { stdio: 'inherit' })
  }
})()
